### ISSUE TITLE
What is Y?

### ISSUE THREAD

**Issue by ajcj151** [basil00/pairgen#1]
https://github.com/basil00/pairgen/blob/6113d7137dfe4cdcb0c850f667dba7a69684b448/pairgen.c#L1320

Hello, I'm trying to figure out what exactly this program does, can you give a brief explanation? Thank you and interesting code.

**Comment by basil00** [comment]
This program works by calculating long chains of related addresses, such that: addr<sub>i</sub> = f(addr<sub>i-1</sub>) for some function f.

Eventually, it should find two different chains that start from different input addr<sub>0</sub> but end in the same output address.  This means that a collision occurred somewhere along the chains, and the chains got merged.  This is represented by "Y", since "Y" kind of looks like two chains merging into 1.

Once a "Y" has been found, the program attempts to find the exact collision point by calculating shorter and shorter chains with the same colliding inputs.

**Comment by ajcj151** [comment]
Man you're fucking awesome! Thanks for your explanation, i understand a little bit, it will be cool make a documentation of project, or any pseudocode representing the core of the program. Again thanks!
